### ISSUE TITLE
ERROR in ./~/css-loader!./~/less-loader!./src/browser/components/main.less

### ISSUE THREAD

**Issue by iwd-sys** [sqren/fb-sleep-stats#72] opened 2016-03-04 11:09 UTC
Hello,

I tried from Debian Jessie and Ubuntu 15 and I got he following error running `npm run webpack`

```
> fb-sleep-stats@0.9.0 webpack /home/foobar/Perso/fb-sleep-stats
> webpack --progress

Hash: 147f09ea085f470e6c24  
Version: webpack 1.12.14
Time: 14950ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.18 MB       0  [emitted]  main
    + 336 hidden modules

ERROR in ./~/css-loader!./~/less-loader!./src/browser/components/main.less
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/foobar/Perso/fb-sleep-stats/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/foobar/Perso/fb-sleep-stats/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/home/foobar/Perso/fb-sleep-stats/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/home/foobar/Perso/fb-sleep-stats/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/browser/components/main.less 4:14-127
```

Furthermore, `npm install` gave an optional dep error : 

```
npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})

> react-router@2.0.0 postinstall /home/foobar/Perso/fb-sleep-stats/node_modules/react-router
> node ./npm-scripts/postinstall.js

npm WARN optional dep failed, continuing fsevents@1.0.8
```

**Comment by sorenlouv** [comment] 2016-03-04 11:59
This is a duplicate of https://github.com/sqren/fb-sleep-stats/issues/36. Please let me know if you continue having problems. I'll close this for now.

**Closed as completed by sorenlouv** 2016-03-04 11:59 UTC
