### ISSUE TITLE
localhost:3000

### ISSUE THREAD

**Issue by ajita-asthana** [sqren/fb-sleep-stats#121] opened 2018-07-15 17:54 UTC
I am just getting a search bar on my screen without any list of users.
There is no adblocker enabled
Also after running npm run scrape, the number of  friends is way lesser than that on my friend list.

Any solution?
![screen shot 2018-07-15 at 11 24 18 pm](https://user-images.githubusercontent.com/16641779/42736617-43627ab4-8886-11e8-81d3-a47a9480dfdb.png)

**Comment by sorenlouv** [comment] 2018-07-15 22:17
Hi @ajita-asthana,

This looks like a duplicate of https://github.com/sqren/fb-sleep-stats/issues/119 so will close. Let me know if this is not the case and I will re-open.

**Closed as completed by sorenlouv** 2018-07-15 22:17 UTC

**Comment by glennroast** [comment] 2018-12-05 03:16
I am getting the same issue, blank window with no users apart from the search, which does nothing, it's not the same issue as having the data on the right and no search working on the left. Same screen as previous user on this thread. Can you please help? Good work by the way, would love to get this running!
