### ISSUE TITLE
Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://

### ISSUE THREAD

**Issue by fmamf** [sqren/fb-sleep-stats#118] opened 2018-03-23 19:11 UTC
What should i do in this case? 

- I am using mac

**Comment by sorenlouv** [comment] 2018-07-15 22:20
Hi @fmamf,

This looks like a duplicate of #117 so will close. Let me know if this is not the case and I will re-open.

**Closed as completed by sorenlouv** 2018-07-15 22:20 UTC
