### ISSUE TITLE
npm run webpack: ERROR in ./~/css-loader

### ISSUE THREAD

**Issue by g1lby** [sqren/fb-sleep-stats#66] opened 2016-03-03 21:33 UTC
Hello everyone,

just discovered this amazing project and wanted to instantly kickstart it on my CentOS machine.
Kernel: x86_64 Linux 2.6.32-042stab092.3
Shell: bash 4.1.2
CPU: AMD Opteron 6128 @ 1.5GHz
RAM: 637MiB / 2048MiB

I cloned the project to /usr/src, so I'm working from /usr/src/fb-sleep-stats.
After I filled in the proper variables in the config file, I installed the dependencies via npm as described which went fine.
Unfortunately, npm run webpack breaks with the following error:
[root@***\* fb-sleep-stats]# npm run webpack

> fb-sleep-stats@0.9.0 webpack /usr/src/fb-sleep-stats
> webpack --progress

Hash: ea47e0ea2c32fd949f96
Version: webpack 1.12.14
Time: 20269ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.18 MB       0  [emitted]  main
    + 336 hidden modules

ERROR in ./~/css-loader!./~/less-loader!./src/browser/components/main.less
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/usr/src/fb-sleep-stats/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/usr/src/fb-sleep-stats/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/usr/src/fb-sleep-stats/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/usr/src/fb-sleep-stats/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/browser/components/main.less 4:14-127

Am I doing something wrong?
Cheers,
g1lby

**Comment by sorenlouv** [comment] 2016-03-03 21:50
Hi,
This is a duplicate of https://github.com/sqren/fb-sleep-stats/issues/36. Please let me know if you continue having problems. I'll close this for now.

**Closed as completed by sorenlouv** 2016-03-03 21:50 UTC
